MiniJavaInScala/mjis

- src/main/java/mjis/GccRunner.scala
- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Compiler.scala
- src/main/scala/mjis/asm/AsmProgram.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/test/scala/mjis/AsmTestHelper.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
> Split code generation from register allocation

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Compiler.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/IntegrationTest.scala
> Add naive register allocator

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/Instruction.scala
> Move addressing of AR operands to register allocator

- src/main/scala/mjis/Lexer.scala
- src/test/scala/mjis/LexerTest.scala
Don't mind me, I'm just scratching this pet peeve of mine...
> Add support for single-line comments

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
Patterns for now: inc, dec, address modes
-20% on fannkuch \o/
> Bottom-up pattern matching

- src/main/java/mjis/GccRunner.scala
- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/CLIMain.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Compiler.scala
- src/main/scala/mjis/Config.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
Note that the default name of the assembler file will now be "a.out.s"
> Add -o output file cmdline option

- src/main/scala/mjis/CodeGenerator.scala
Restricts those pesky ActivationRecordOperands to a single location in
CodeGenerator
> CodeGenerator: Assign stack parameters to virtual registers

- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/CommonSubexpressionElimination.scala
- src/main/scala/mjis/opt/ConstantFolding.scala
- src/main/scala/mjis/opt/Identities.scala
- src/main/scala/mjis/opt/LoopStrengthReduction.scala
- src/main/scala/mjis/opt/Normalization.scala
- src/main/scala/mjis/opt/Optimization.scala
- src/main/scala/mjis/opt/TrivialPhiElimination.scala
Actually saves a few phi operands in fannkuch, but nothing measurable
> Iterate optimizations until a fixpoint is reached

- src/test/scala/mjis/LivenessIntervalTest.scala
This brings the test coverage for LivenessIntervals (minus toString methods) to 100% line coverage, so we can more confidently implement optimizations to the data structures.
> Add more tests for LivenessIntervals

- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/ConstantFolding.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/opt/FirmExtractors.scala
- src/main/scala/mjis/opt/Identities.scala
- src/main/scala/mjis/opt/RedundantLoadElimination.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/FirmGraphTestHelper.scala
- src/test/scala/mjis/opt/RedundantLoadEliminationTest.scala
Shaves something like 5% off fannkuch
Note that non-local elimination would also be possible: http://blog.llvm.org/2009/12/introduction-to-load-elimination-in-gvn.html
> Implement Redundant Load Elimination with rudimentary aliasing analysis

- src/main/scala/mjis/FirmConstructor.scala
- src/main/scala/mjis/Optimizer.scala
More flexible than avoiding them in FirmConstructor
> Remove Critical Edges in Optimizer

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/test/scala/mjis/AsmTestHelper.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
http://stackoverflow.com/questions/21835117/function-code-aligned-to-16-bytes
Fixes #273.
> Align labels reachable by jumps to 16 bytes.

- assets/libfirm_entry.c
Having it only laying around on my computer is bad style, after all.
> Add code for libfirm.so bootstrap

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/main/scala/mjis/opt/FirmExtractors.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/RegisterAllocatorTest.scala
Also finally make AddressOperand params RegisterOperands
Another ~8% off of fannkuch
> Ultimate address mode matching

- src/main/scala/mjis/opt/LoopStrengthReduction.scala
Reduces the applications in fannkuch to 0
> Severely limit LoopStrengthReduction to avoid increasing register pressure

- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/LivenessInterval.scala
- src/test/scala/mjis/LivenessIntervalTest.scala
- src/test/scala/mjis/RegisterAllocatorTest.scala
Just one of multiple possible split position optimizations.
> Move spill positions out of loops

- assets/divByConst-test.mj
- src/main/scala/mjis/CLIMain.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Config.scala
- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/main/scala/mjis/opt/Identities.scala
- src/main/scala/mjis/util/PowerOfTwo.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/IntegrationTest.scala
Have to think about MIN_INT again, but it wouldn't be a loss without it, I guess
> Div by const

- src/main/scala/mjis/CallGraph.scala
- src/main/scala/mjis/FirmConstructor.scala
- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/opt/Inlining.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/FirmGraphTestHelper.scala
> Call graph data structure

- src/main/scala/mjis/Compiler.scala
- src/main/scala/mjis/PeepholeOptimizer.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/test/scala/mjis/PeepholeOptimizerTest.scala
(This is just a newly-rebased version of #323 which was already reviewed and LGTM'd by @Kha)
> Implement peephole optimizations

- src/main/scala/mjis/CodeGenerator.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
(Fix by @Kha, I'm just implementing it.)
> Generate code for access to uninitialized arrays

- assets/System_out_println_64.c
- lib/stdlib/System_out_println_64.s
- lib/stdlib/main_64.s
> Add proper buffering to System_out_println

- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/Inlining.scala
This should be a no-brainer, assuming travis passes.
> Turn on DCE

- src/main/scala/mjis/opt/ConstantFolding.scala
- src/main/scala/mjis/opt/FirmExtractors.scala
- src/main/scala/mjis/opt/Identities.scala
> Fix constant folding bug, add many more identities

- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/LoopInvariantCodeMotion.scala
- src/main/scala/mjis/opt/Optimization.scala
- src/main/scala/mjis/util/Digraph.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/opt/LoopInvariantCodeMotionTest.scala
Sebastian's version with a fix. Passes on my machine.
> Loop Invariant Code Motion

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/BlockOrdering.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/test/scala/mjis/AsmTestHelper.scala
- src/test/scala/mjis/PeepholeOptimizerTest.scala
Also get rid of BasicBlockOperand, which is a relict from an old
register allocator.
> Add Label instruction and generator for unique labels inside a block.

- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/opt/ConditionalMoveTest.scala
Also use notOptimize instead of strange optimizeTo hacks.
> Extend optimizeUnreachableGraphs = true to OptimizerMatcher.
