- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/opt/NodeCollector.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/opt/FirmExtensionsTest.scala
Something like -10% time for fannkuch on my machine
> CodeGenerator: block linearization via reverse post-order

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/FirmConstructor.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
Another ~7% speedup \o/
Partially reverts 6a568e, including that horrible global state (who
ever thought that would be a good idea?)
> CodeGenerator: Don't emit unnecessary jmps

- src/main/scala/mjis/opt/FirmExtensions.scala
This prevents code generation for unreachable blocks.
> Don't visit Bad nodes during getBlockBackEdges.

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/PhiCodeGenerator.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/Instruction.scala
- src/test/scala/mjis/PhiCodeGeneratorTest.scala
We'll need the PhiCodeGenerator to generate more parallel/interdependent moves (spill moves and moves between split intervals) in the upcoming register allocator.
> Support for AR operands and varying operand sizes in PhiCodeGenerator

- src/main/scala/mjis/RegisterAllocator.scala
Those were meant as debug information.
> Remove instruction comments generated by the register allocator.

- src/main/scala/mjis/opt/ConstantFolding.scala
This would lead to an exception when trying to generate a lea
instruction with constant offset (or is it index?)
> Fix shl with constant arguments not being folded

- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/LivenessInterval.scala
- src/test/scala/mjis/LivenessIntervalTest.scala
e.g. intersection test of two liveness intervals is now linear
instead of quadratic in the number of ranges. Gave a ~15% speedup
for register allocation when compiling fannkuch.
> Improve data structures and algorithms for LivenessIntervals.

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/DataFlowAnalysis.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/opt/NodeCollector.scala
- src/main/scala/mjis/util/Digraph.scala
- src/main/scala/mjis/util/MapExtensions.scala
- src/test/scala/mjis/util/DigraphTest.scala
The only (small) generated assembler difference is that Bad nodes may now induce critical edges elimination. But I guess handling/not emitting dead code is a general problem still to be tackled.
> Find loops via SCCs

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/test/scala/mjis/RegisterAllocatorTest.scala
Includes a poor man's peephole optimization in the AssemblerFileGenerator
> Use register hints to avoid unnecessary movs

- src/main/scala/mjis/opt/ConstantFolding.scala
- src/main/scala/mjis/opt/Identities.scala
Without this, certain interactions with inlining will result in Store or Load nodes complaining about loading addresses that have a mode != P64.
> Properly handle NULL array accesses in optimizations

- src/main/scala/mjis/AssemblerFileGenerator.scala
- src/main/scala/mjis/BlockOrdering.scala
- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Compiler.scala
- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/Phase.scala
- src/main/scala/mjis/RegisterAllocator.scala
- src/main/scala/mjis/asm/AsmProgram.scala
- src/main/scala/mjis/opt/DataFlowAnalysis.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/util/Digraph.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
- src/test/scala/mjis/util/DigraphTest.scala
```
 perf stat ./a.out                     
556355
51
Performance counter stats for './a.out':
5234.982690      task-clock (msec)         #    1.000 CPUs utilized          
12      context-switches          #    0.002 K/sec                  
8      cpu-migrations            #    0.002 K/sec                  
4      page-faults               #    0.001 K/sec                  
16,697,532,792      cycles                    #    3.190 GHz                    
4,289,009,585      stalled-cycles-frontend   #   25.69% frontend cycles idle   
<not supported>      stalled-cycles-backend   
30,563,451,088      instructions              #    1.83  insns per cycle        
3,066,129,977      branches                  #  585.700 M/sec                  
184,433,206      branch-misses             # …
```
> Re-optimize block order after register allocation

- src/main/scala/mjis/opt/CommonSubexpressionElimination.scala
- src/main/scala/mjis/opt/ConstantFolding.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/opt/Identities.scala
- src/main/scala/mjis/opt/LoopStrengthReduction.scala
- src/main/scala/mjis/opt/Normalization.scala
- src/main/scala/mjis/opt/Optimization.scala
- src/main/scala/mjis/opt/RedundantLoadElimination.scala
- src/main/scala/mjis/opt/TrivialPhiElimination.scala
* Node-based optimizations can automatically be fixpoint-iterated and
modify the graph immediately
* Graph-based optimizations with their own walkers need their changes
to be deferred for the consistency of the remaining walk
Possible further optimization: Fold all node-based optimizations into
one fixpoint iteration
> Split Optimizations into graph-based and node-based ones

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/asm/Instruction.scala
Assembly/Compiler Coding Rule 33. (M impact, H generality) INC and DEC instructions should
be replaced with ADD or SUB instructions, because ADD and SUB overwrite all flags, whereas INC and
DEC do not, therefore creating false dependencies on earlier instructions that set the flags.
> CodeGenerator: Remove inc/dec generation because Intel says so

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/opt/LoopStrengthReduction.scala
master:
```
Performance counter stats for './a.out':
4223.180470      task-clock (msec)         #    1.001 CPUs utilized          
7      context-switches          #    0.002 K/sec                  
7      cpu-migrations            #    0.002 K/sec                  
4      page-faults               #    0.001 K/sec                  
13,582,187,111      cycles                    #    3.216 GHz                    
3,299,954,381      stalled-cycles-frontend   #   24.30% frontend cycles idle   
<not supported>      stalled-cycles-backend   
22,591,029,200      instructions              #    1.66  insns per cycle        
3,065,913,294      branches                  #  725.973 M/sec                  
188,173,583      branch-misses             #    6.14% of all branches        
4.220724362 …
```
> Poor man's instruction scheduling for induction variables

- src/main/scala/mjis/FirmConstructor.scala
- src/main/scala/mjis/opt/Identities.scala
- src/test/scala/mjis/FirmConstructorTest.scala
Memory outputs of Div/Mod are only relevant for division by zero, whose
result is undefined anyway. As memory edges introduce "false"
dependencies into the graph, eliminating them improves the visiting
order, potentially generating less spills.
> Don't set current memory when generating Div and Mod nodes.

- src/main/scala/mjis/RegisterAllocator.scala
- src/test/scala/mjis/RegisterAllocatorTest.scala
The registers being freed must of course be selected from all occupied
registers, not from occupiedRegNrsWithoutPhi.
> Fix not enough registers being freed for Phi generation.

- src/main/scala/mjis/CodeGenerator.scala
- src/main/scala/mjis/Optimizer.scala
- src/main/scala/mjis/opt/FirmExtensions.scala
- src/main/scala/mjis/opt/Inlining.scala
This avoid allocating and discarding an ArrayBuffer of nodes every time.
> Add NodeWalker for walking nodes without storing them.

- src/main/scala/mjis/asm/LivenessInterval.scala
- src/test/scala/mjis/LivenessIntervalTest.scala
Inserting a range that was contained in an existing one would leave the
interval in the ranges map with a wrong key.
> Fix LivenessInterval.addRange when inserting overlapping ranges.

- src/main/scala/mjis/Optimizer.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
```
 ./run.sh mj-test/run/MMul.mj --timings
Lexer/Parser: 90 ms
Namer: 24 ms
Typer: 6 ms
FirmConstructor: 85 ms
Identities$:	3 ms	
ConstantFolding$:	12 ms	
Normalization$:	0 ms	
CommonSubexpressionElimination$:	7 ms	
TrivialPhiElimination$:	1 ms	
LoopStrengthReduction$:	12 ms	
RedundantLoadElimination$:	0 ms	
PureFunctionCallElimination$:	0 ms	
LoopInvariantCodeMotion$:	8 ms	
ConditionalMoves$:	0 ms	
Identities$:	2 ms	
ConstantFolding$:	7 ms	
Normalization$:	0 ms	
CommonSubexpressionElimination$:	4 ms	changed!
TrivialPhiElimination$:	1 ms	
LoopStrengthReduction$:	4 ms	
RedundantLoadElimination$:	3 ms	
PureFunctionCallElimination$:	1 ms	
LoopInvariantCodeMotion$:	13 ms	changed!
ConditionalMoves$:	0 ms	
Identities$:	1 ms	
ConstantFolding$:	6 ms	
Normalization$:	0 ms …
```
> Try to optimize Optimization a bit

- src/main/scala/mjis/Config.scala
- src/main/scala/mjis/Optimizer.scala
- src/test/scala/mjis/CodeGeneratorTest.scala
- src/test/scala/mjis/CompilerTestMatchers.scala
Fixes the CodeGenerator tests. The recursive inlining test is adapted to
the fact that we can't exclude UnusedParameterElimination any more.
> Add option to optimize all graphs (not just reachable) for testing.

- src/main/scala/mjis/asm/Instruction.scala
The READ for RAX leads to RAX being treated as "live" until the
beginning of the function, effectively blocking it for other uses
> Fix OperandSpec of DivMod instruction.
